### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by cgarciae** [pprzetacznik/IElixir#12]
It might be a lot easier to distribute through a Docker container since you control the whole environment.

**Comment by pprzetacznik** [comment]
@cgarciae It sounds like a good idea. Could you provide more details about your vision? Is it about setting up distributed cloud in docker with configured images of IElixir instances?

**Comment by mattvonrocketstein** [comment]
There is nothing distributed/cloud about it, but [here is a start](https://mattvonrocketstein.github.io/heredoc/ielixir-notebook-in-docker.html).

**Comment by schuster-rainer** [comment]
https://github.com/nbgallery/jupyter-docker

**Comment by pprzetacznik** [comment]
I've created a docker container containing the newest version of IElixir based on stable OTP/Elixir and Jupyter versions. You can see it here: https://hub.docker.com/r/pprzetacznik/ielixir/.

I've also added some notes to the README.md file: https://github.com/pprzetacznik/IElixir#docker. Please take a look and feel free to give an opinion on that. Please keep on mind that the full docker image takes about 1,5GB which is pretty big. I was trying to make this smaller but there are many dependencies for Erlang and Jupyter as well. I'm open to suggestions if some other docker images are needed for experiments.
