### ISSUE TITLE
Kernel crash: GenServer terminates on SQLite 'no such table:main.history' error

### ISSUE THREAD

**Issue by dabro** [pprzetacznik/IElixir#14]
I keep getting this intermittently.  It's difficult to evaluate more than 5 cells without crashing.  I had an install since Jan that worked well; I reformatted and reinstalled in last week.

Any thoughts?

2016-05-12 15:20:23.336 [error] GenServer #PID<0.180.0> terminating
*\* (ArgumentError) raise/1 expects an alias, string or exception as the first argument, got: {:sqlite_error, 'no such table: main.history'}
    (ecto) lib/ecto/adapters/sql.ex:197: Ecto.Adapters.SQL.query/5
    (ecto) lib/ecto/adapters/sql.ex:456: Ecto.Adapters.SQL.model/5
    (ecto) lib/ecto/repo/model.ex:71: anonymous fn/11 in Ecto.Repo.Model.insert/4
    (ecto) lib/ecto/repo/model.ex:303: anonymous fn/3 in Ecto.Repo.Model.wrap_in_transaction/8
    (ecto) lib/ecto/pool.ex:292: Ecto.Pool.with_rollback/2
    (ecto) lib/ecto/adapters/sql.ex:546: Ecto.Adapters.SQL.transaction/8
    (ecto) lib/ecto/pool.ex:244: Ecto.Pool.outer_transaction/6
    (ecto) lib/ecto/adapters/sql.ex:515: Ecto.Adapters.SQL.transaction/3

**Comment by pprzetacznik** [comment]
@dabro Could you provide me version of Elixir and Erlang you're using?

**Comment by dabro** [comment]
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

IEx 1.2.5

installed with homebrew

**Comment by dabro** [comment]
Over the last couple days, I've gotten a sense of the problem.  It seems to only occur when cells are rapidly evaluated one after the other.  If you are working on one, or just a very few cells, iteratively, the kernel won't crash.

**Comment by dabro** [comment]
It looks like something backs up.  When I evaluate a cell, the tab title shifts from "{my file name}" to "(Busy) {my file name}".  If I evaluate another cell it becomes "(Busy) (Busy) {my file name}", and so on.

If I click into a cell to edit, the "(Busy)" drops off the title.  I don't know if this reflects an underlying kernel state, or is just the notebook javascript.

**Comment by pprzetacznik** [comment]
@dabro I've recently seem some problems with SQlite, could you test this with the newest version of elixir?
