### ISSUE TITLE
Jupyter Hydrogen Support?

### ISSUE THREAD

**Issue by beginrescueend** [pprzetacznik/IElixir#18]
This looks like a really cool Elixir Jupyter project!

I was wondering if there was a way to interact with Hydrogen? https://github.com/nteract/hydrogen

Hydrogen takes Jupyter Kernels and makes them work with the Atom editor, interactively.

I wonder if all it would take is a config file, script, or apm setting.

Thanks for a great project!

**Comment by beginrescueend** [comment]
I may have answered my own question, by trying something:
  I re-ran `apm install hydrogen` and restarted `atom`

Now, iElixir is running in Hydrogen!

I reported it here, as well: https://github.com/nteract/hydrogen/issues/354

(screen shot, below)

![screen shot 2016-07-15 at 2 26 42 pm](https://cloud.githubusercontent.com/assets/8292133/16886160/37633826-4a98-11e6-8f2e-5b2b7b778628.png)

**Comment by pprzetacznik** [comment]
@beginrescueend That's amazing, thanks for posting this info!
