### ISSUE TITLE
Can't compile on FreeBSD 10/11

### ISSUE THREAD

**Issue by yggdr** [pprzetacznik/IElixir#26]
Hi,

new to the whole Elixir thing, so a Jupyter kernel would be great, but I have two problems installing IElixir:

1) mix uses the `make` command, which isn't  GNU make on FreeBSD, and I didn't find a possibility to specify something like MAKE=gmake. I was able to circumvent this by creating a softlink in ~/bin adding that to the front of my PATH.

2) `mix test` fails with
make[3]: Entering directory '/root/IElixir/deps/erlzmq/deps/zeromq3/src'
  CXX    libzmq_la-decoder.lo
In file included from decoder.cpp:32:
./i_msg_sink.hpp:32:5: error: 'i_msg_sink' defined as a struct here but previously declared as a class [-Werror,-Wmismatched-tags]
    struct i_msg_sink
    ^
./decoder.hpp:38:5: note: did you mean struct here?
    class i_msg_sink;
    ^~~~~
    struct
./i_decoder.hpp:29:5: note: did you mean struct here?
    class i_msg_sink;
    ^~~~~
    struct
1 error generated.
This seems to be an error in erlzmq, but compiling that manually didn't work either.
Any suggestions? Thanks!

Erlang/OTP 19 [erts-8.1.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.3.4

**Comment by pprzetacznik** [comment]
Hi @yggdr, can you test it one more time? I've fixed support for younger elixir/otp versions.
