### ISSUE TITLE
Add support for Elixir 1.4.x

### ISSUE THREAD

**Issue by notexistence** [pprzetacznik/IElixir#28]
Currently, tests are fails for Elixir 1.4.0 and higher.

```
warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  mix.exs:14

warning: variable "package" does not exist and is being expanded to "package()", please use parentheses to remove the ambiguity or change the variable name
  mix.exs:18

(Mix) You're trying to run :ielixir on Elixir v1.4.0 but it has declared in its mix.exs file it supports only Elixir >= 1.1.0 and < 1.4.0
```

**Comment by pprzetacznik** [comment]
It should work right now, thx for the report. Please let me know if it works right now.

**Comment by anandtrex** [comment]
I tried running it with elixir 1.5.1 (after bumping up the version in mix.exs). When I run `mix test`, there is one test failure. (See [test-log.txt](https://github.com/pprzetacznik/IElixir/files/1312208/test-log.txt)). Apart from that everything seems to work fine. I'm able to open the notebook and run code in it.

**Comment by conradwt** [comment]
@anandtrex It may be better if you provided a link to the output like a gist instead of a link which initiate a download within the browser.

**Comment by anandtrex** [comment]
@conradwt I've moved the contents to this gist: [test-log.txt](https://gist.github.com/anandtrex/6f2b29539b311d99e9a4e9e61b251213)

**Comment by conradwt** [comment]
@anandtrex Great, thanks.

**Comment by pprzetacznik** [comment]
@anandtrex thx for you input. I'll sit on this by the end of this week, I'll go through updating elixir to 1.5 and check this carefully.

**Comment by pprzetacznik** [comment]
@anandtrex this is fixed now. Thx for your notification.
