### ISSUE TITLE
mix test fails

### ISSUE THREAD

**Issue by acrogenesis** [pprzetacznik/IElixir#34]
Running mix test gives:

```
** (Mix) Could not compile dependency :erlzmq, "make" command failed. You can recompile this dependency with "mix deps.compile erlzmq", update it with "mix deps.update erlzmq" or clean it with "mix deps.clean erlzmq"
```
Running `mix deps.compile erlzmq` gives the same error.
Running `mix deps.update erlzmq` gives:
```
* Updating erlzmq (https://github.com/zeromq/erlzmq2.git)
Resolving Hex dependencies...
Dependency resolution completed:
  certifi 2.0.0
  decimal 1.1.2
  earmark 0.2.1
  ecto 1.1.9
  esqlite 0.2.3
  ex_doc 0.12.0
  excoveralls 0.3.11
  exjsx 3.2.1
  hackney 1.9.0
  idna 5.1.0
  inch_ex 0.4.0
  jsx 2.8.2
  metrics 1.0.1
  mimerl 1.0.2
  pipe 0.0.2
  poison 1.5.2
  poolboy 1.5.1
  quickrand 1.7.2
  sqlite_ecto 1.1.0
  sqlitex 0.8.0
  ssl_verify_fun 1.1.1
  unicode_util_compat 0.3.1
```
But doesn't fix `mix test`
And `mix deps.clean erlzmq` gives: `warning: the dependency erlzmq is not present in the build directory`

`elixir --version`
```
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.2
```

**Comment by shadyproject** [comment]
I was able to get this to work by following the erlzmq2 instructions [here](https://github.com/robbielynch/ierlang/wiki/Installation)

**Comment by pprzetacznik** [comment]
@acrogenesis is there still a problem with compiling erlzmq? I was experimenting with chumak but it seems that chumak is not ready yet.

**Comment by DallanQ** [comment]
I had a similar problem. Manually installing rebar solved it.

**Comment by pprzetacznik** [comment]
@acrogenesis could you check if `rebar` and `rebar3` is properly installed on your machine? Just type `rebar` and `rebar3` in your shell.

**Comment by DallanQ** [comment]
This is an **awesome** thing to have by the way - thank you!

**Comment by IvanShpotenko** [comment]
I had a similar problem. Following @DallanQ, manually installing rebar solved it.
I am new to Erlang and Elixir, so I'll elaborate a bit. I did
`mix local.rebar`
and then added `~/.mix` to PATH ([mix docs](https://hexdocs.pm/mix/Mix.Tasks.Local.Rebar.html)):
`export PATH=$PATH:~/.mix`
And it worked like a charm. 
Thanks @pprzetacznik for the good work!
