### ISSUE TITLE
Mix test fails with esqlite

### ISSUE THREAD

**Issue by ghoetker** [pprzetacznik/IElixir#35]
Trying to install IElixer per the directions.  All seems to go well.  However, mix test emits the following error:

```
** (Mix) Could not compile dependency :esqlite, "/Users/ghoetker/.mix/rebar3 bare compile --paths "/Users/ghoetker/Elixer Projects/IElixir/_build/test/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile esqlite", update it with "mix deps.update esqlite" or clean it with "mix deps.clean esqlite"
```

I have tried mix deps.update esqlite, followed by mix deps.compile esqlite, which generates the same message.  mix deps.clean, followed by mix deps.compile emits the same message too.

Please let me know what other debugging information I can provide. Thank you.

**Comment by pprzetacznik** [comment]
@ghoetker have you tried running `mix deps.compile esqlite`? Can you paste the output of this command?

**Comment by ghoetker** [comment]
Here is the result of running that command.  Thank you!

```
ghoetker/Elixer Projects/IElixir% mix deps.compile esqlite
===> Compiling esqlite
===> Compiling /Users/ghoetker/Elixer Projects/IElixir/deps/esqlite/c_src/esqlite3_nif.c
===> clang: error: no such file or directory: '/Users/ghoetker/Elixer'
clang: error: no such file or directory: 'Projects/IElixir/deps/esqlite/c_src/esqlite3_nif.c'
clang: error: no such file or directory: 'Projects/IElixir/deps/esqlite/c_src/esqlite3_nif.o'
clang: error: no input files

** (Mix) Could not compile dependency :esqlite, "/Users/ghoetker/.mix/rebar3 bare compile --paths "/Users/ghoetker/Elixer Projects/IElixir/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile esqlite", update it with "mix deps.update esqlite" or clean it with "mix deps.clean esqlite"
ghoetker/Elixer Projects/IElixir%
```

**Comment by pprzetacznik** [comment]
@ghoetker my first guess would be to check if the problem is in directory name `Elixer Projects` because in further error lines you can see path which has trimmed first part of the whole path.

Secondly I would check if you have `rebar` and `rebar3` available from the command line.

**Comment by ghoetker** [comment]
@pprzetacznik The space in the directory name was the issue.  After that, all worked wonderfully. As a bonus, installing the kernel also allows using Elixir with the newer Jupyter Lab.  Very cool and thank for you for such a great contribution to the ecosystem.

**Comment by emagdiev5** [comment]
I have same issue but don't have space in directory name, can someone help, what else could cause it
