### ISSUE TITLE
Loading multiple modules with Boyle

### ISSUE THREAD

**Issue by ghost** [pprzetacznik/IElixir#36]
How to load multiple modules with Boyle?
Something like
```elixir
Boyle.install([{:matrex, "~> 0.6"}, {:gen_stage, "~> 0.14"}])
```
or
```elixir
Boyle.install({:gen_stage, "~> 0.14"})
Boyle.install({:matrex, "~> 0.6"})
```
simply return `** (ArgumentError) "argument error"`

**Comment by pprzetacznik** [comment]
@rparcus thanks for reporting this issue. I see the problem in the code which is related to storing dependencies list in deps.lock file.

**Comment by pprzetacznik** [comment]
@rparcus I've fixed this with this commit: https://github.com/pprzetacznik/IElixir/commit/20d880cee1bed6bdcf579e5c42ecbee2dc4703e4

Please check if everything works fine right now. Probably you need to remove your Boyle environment and recreate this once again.

**Comment by ghost** [comment]
looking at the code it should work. I can only check on Monday but thank you so much for the fix and the project. It's quite helpful!

Edit: It's definitely working now. Thanks!
