### ISSUE TITLE
install_script.sh failure

### ISSUE THREAD

**Issue by bjpcjp** [pprzetacznik/IElixir#44]
New Elixir user here. Ubuntu 14.04 LTS.

```
$iex -v:
Erlang/OTP 21 [erts-10.2] 
IEx 1.7.4 (compiled with Erlang/OTP 20)

```
Following the README installation script. ./install_script.sh fails as shown:

```
  mix.exs:22

make: rebar: Command not found
make: *** [compile] Error 127
** (Mix) Could not compile dependency :erlzmq, "make" command failed. You can recompile this dependency with "mix deps.compile erlzmq", update it with "mix deps.update erlzmq" or clean it with "mix deps.clean erlzmq"

```

IEx works as expected from command line. The goal is to install this kernel for Jupyter Notebook usage.

**Comment by bjpcjp** [comment]
solved by reinstalling rebar.

**Comment by vans163** [comment]
If anyone else gets this is because rebar is not in path and rebar3 is.  You can temporary add rebar to path in its default place ~/.mix
