### ISSUE TITLE
IElixir must be ran as root?

### ISSUE THREAD

**Issue by mdsmithson** [pprzetacznik/IElixir#45]
I get this error if I run without root on Ubuntu 18.04

** (File.Error) could not remove files and directories recursively from "/home/user/Documents/IElixir/_build/prod/lib/ielixir/priv": permission denied
    (elixir) lib/file.ex:1252: File.rm_rf!/1
    (mix) lib/mix/project.ex:646: Mix.Project.symlink_or_copy/3
    (mix) lib/mix/project.ex:639: Mix.Project.build_structure/2
    (mix) lib/mix/tasks/compile.all.ex:20: Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.ex:96: Mix.Tasks.Compile.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/tasks/app.start.ex:58: Mix.Tasks.App.Start.run/1

**Comment by pprzetacznik** [comment]
Hi @mdsmithson!

Can you share what exactly do you run? There is `File.rm_rf / 1` function invocation in Boyle module. Have you installed IElixir as the root or have you done anything as the root during the installation?

**Comment by mdsmithson** [comment]
Indeed that was the issue. Thank you!
