### ISSUE TITLE
kernel crashing

### ISSUE THREAD

**Issue by mattvonrocketstein** [pprzetacznik/IElixir#6]
This won't quite work for me, but I don't have a lot of information available to debug it.  Ever seen anything like this?  The crash occurs before I try to even use the front-end, and the shutdown/restart attempts after I'm entering input on the webpage.  I'm running on Elixir 1.1.0 and jupyter 4.0.6, ubuntu.

```
 $ jupyter console --kernel ielixir
enif_send: env==NULL on non-SMP VM/home/vagrant/code/IElixir/start_script.sh: line 15:  9698 Aborted                 (core dumped) CONNECTION_FILE=$1 mix run --no-halt
Jupyter Console 4.0.3

[ZMQTerminalIPythonApp] Loading IPython extension: storemagic
ERROR: Kernel did not respond

Shutting down kernel
ERROR: Kernel did not respond

Shutting down kernel
```

**Comment by pprzetacznik** [comment]
Hi @mattvonrocketstein,

could you perform `mix test` and paste here the output?

**Comment by mattvonrocketstein** [comment]
No failures there

```
Finished in 0.3 seconds (0.2s on load, 0.1s on tests) 16 tests, 0 failures
```

**Comment by pprzetacznik** [comment]
Would you mind to try to run integration tests with:

``` Bash
$ git clone https://github.com/pprzetacznik/jupyter_kernel_test/tree/ielixir
$ python test_ipython.py
```

and check if everything is ok? Probably this can show more errors.

**Comment by mattvonrocketstein** [comment]
Closing this issue as I can no longer reproduce.  Maybe it was due to older jupyter versions.
