### ISSUE TITLE
Setting tabSize to 2 instead of 4

### ISSUE THREAD

**Issue by kashifrazzaqui** [pprzetacznik/IElixir#7]
Is there a way to do this?

**Comment by pprzetacznik** [comment]
Could you provide me with more details? Do you have this problem in Jupyter Notebook?

**Comment by kashifrazzaqui** [comment]
@pprzetacznik yes, the notebook indents to 4 spaces but Elixir convention indicates 2. I was wondering if there is something that can be done about this?

**Comment by pprzetacznik** [comment]
@kashifrazzaqui Thank you for reporting this. I believe this is on Jupyter's side. I will try to inspect this and try to figure out the solution.

**Comment by kashifrazzaqui** [comment]
Thanks

**Comment by pprzetacznik** [comment]
Hi @kashifrazzaqui,

I found some kind of workaround for this problem: http://jupyter-notebook.readthedocs.org/en/latest/frontend_config.html#how-front-end-configuration-works

While you have Jupyter Notebook opened you can type this code into your JS Console in your browser (right mouse button on the website and pick "Inspect element", then turn on "console" tab):

``` javascript
var cell = Jupyter.notebook.get_selected_cell();
var config = cell.config;
var patch = {
      CodeCell:{
        cm_config:{indentUnit:2}
      }
    }
config.update(patch)
```

I will try to check if I can set it permanently for IElixir kernel but I'm not sure if it's possible.

Cheers!

**Comment by pprzetacznik** [comment]
I have put proper config to kernel.js file which is used by Jupyter after loading. Please reinstall your IElixir from master branch to see changes.
